@echo off

start cmd /k "python RFhelper.py"
start cmd /k "python RFFL-server.py"
start cmd /k "python RFFL-clients0.py"
start cmd /k "python RFFL-clients1.py"
start cmd /k "python RFFL-clients2.py"
start cmd /k "python RFFL-clients3.py"
start cmd /k "python RFFL-clients4.py"
start cmd /k "python RFFL-clients5.py"
start cmd /k "python RFFL-clients6.py"
start cmd /k "python RFFL-clients7.py"
start cmd /k "python RFFL-clients8.py"
start cmd /k "python RFFL-clients9.py"
start cmd /k "python RFFL-clients10.py"
start cmd /k "python RFFL-clients11.py"
start cmd /k "python RFFL-clients12.py"
start cmd /k "python RFFL-clients13.py"
start cmd /k "python RFFL-clients14.py"
start cmd /k "python RFFL-clients15.py"
start cmd /k "python RFFL-clients16.py"
start cmd /k "python RFFL-clients17.py"
start cmd /k "python RFFL-clients18.py"
start cmd /k "python RFFL-clients19.py"
start cmd /k "python RFFL-clients20.py"
start cmd /k "python RFFL-clients21.py"
start cmd /k "python RFFL-clients22.py"
::start cmd /k "python RFFL-clients23.py"