@echo off

start cmd /k "python helperUnary.py"
start cmd /k "python FL-server.py"
start cmd /k "python FL-clients0.py"
start cmd /k "python FL-clients1.py"
start cmd /k "python FL-clients2.py"
start cmd /k "python FL-clients3.py"
start cmd /k "python FL-clients4.py"
start cmd /k "python FL-clients5.py"
start cmd /k "python FL-clients6.py"
start cmd /k "python FL-clients7.py"
start cmd /k "python FL-clients8.py"
start cmd /k "python FL-clients9.py"
start cmd /k "python FL-clients10.py"
start cmd /k "python FL-clients11.py"
start cmd /k "python FL-clients12.py"
start cmd /k "python FL-clients13.py"
start cmd /k "python FL-clients14.py"
start cmd /k "python FL-clients15.py"
start cmd /k "python FL-clients16.py"
start cmd /k "python FL-clients17.py"
start cmd /k "python FL-clients18.py"
start cmd /k "python FL-clients19.py"
start cmd /k "python FL-clients20.py"
start cmd /k "python FL-clients21.py"
start cmd /k "python FL-clients22.py"
::start cmd /k "python FL-clients23.py"